name: Compile

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

permissions:
  contents: read

concurrency:
  group: ${{ github.workflow }}-${{ github.ref || github.run_id }}
  cancel-in-progress: true

jobs:
  msvc2022:
    runs-on: windows-2025
    strategy:
      matrix:
        build_type: [Release]
        architecture: [Win32]

    steps:
      - uses: actions/checkout@v3
      - name: Run CMake
        run: cmake -S . -B build -G "Visual Studio 17 2022" -A ${{ matrix.architecture }}
        if: matrix.build_type == 'Release'
      - name: Build
        run: cmake --build build --config ${{ matrix.build_type }} --parallel 10